controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Teachers;
use app\models\Pdfs;
use yii\web\UploadedFile;
use yii\helpers\Url;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('home');
    }

    public function actionAdd()
    {
        $teacher = new Teachers();
        $pdf = new Pdfs();

        $formData = Yii::$app->request->post();

        if($teacher->load($formData) && $pdf->load($formData)){

            $imageName = $teacher->name;

            if ($teacher->file = UploadedFile::getInstance($teacher, 'file')) {
                $teacher->file->saveAs('img/'.$imageName.'.'.$teacher->file->extension);
                //save the path in DB..
                $teacher->photo = '/img/'.$imageName.'.'.$teacher->file->extension;
            }

            if ($pdf->file = UploadedFile::getInstance($pdf, 'file')) {
                $pdf->file->saveAs('pdf/'.$pdf->file);
                //save the path in DB..
                $pdf->teachername = $teacher->name;
                $pdf->pdfname = $pdf->file; 
                $pdf->pdf = '/pdf/'.$pdf->file;
                $pdf->save();
            }
            
            
            if($teacher->save()){
                Yii::$app->getSession()->setFlash('message', 'Добавлено');
                return $this->redirect(['pm1']);
            }else{
                Yii::$app->getSession()->setFlash('message', 'Не удалось добавить');

            }
        }
        return $this->render('add', ['teacher' => $teacher, 'pdf' => $pdf]);
    }

    public function actionUpdate($id){
        $teacher = Teachers::findOne($id);
        $pdfs = Pdfs::find()->all();
        $pdf = new Pdfs();
        $formData = Yii::$app->request->post();

        if ($pdf->load($formData) && $pdf->file = UploadedFile::getInstance($pdf, 'file')) {
            $pdf->file->saveAs('pdf/'.$pdf->file);
            //save the path in DB..
            $pdf->teachername = $teacher->name;
            $pdf->pdfname = $pdf->file; 
            $pdf->pdf = '/pdf/'.$pdf->file;
            $pdf->save();
        }

        if($teacher->load(Yii::$app->request->post()) && $teacher->save()){
            Yii::$app->getSession()->setFlash('message', 'Изменено');
            return $this->redirect(['pm1', 'id' => $teacher->id]);
        }

        return $this->render('update', ['teacher' => $teacher, 'pdf' => $pdf, 'pdfs' => $pdfs]);
    }

    public function actionView($id){
        $teacher = Teachers::findOne($id);
        $pdfs = Pdfs::find()->all();
        return $this->render('view', ['teacher' => $teacher, 'pdfs' => $pdfs]);
    }

    public function actionDownload($filename){
        $path = "C:\\xampp\htdocs\baishev\web".$filename;
        if(file_exists($path)){
            return Yii::$app->response->sendFile($path);
        }
    }

    public function actionDelete2($tid, $pdfid){
        
        
        $pdf = Pdfs::findOne($pdfid)->delete();
        if($pdf){
            
            Yii::$app->getSession()->setFlash('message', 'Удалено');
            return $this->redirect(['update', 'id' => $tid]);
        }
    }

    public function actionDelete($id){
        
        
        $teacher = Teachers::findOne($id)->delete();
        if($teacher){
            
            Yii::$app->getSession()->setFlash('message', 'Удалено');
            return $this->redirect(['pm1']);
        }
    }

    public function actionPhysmath()
    {
        return $this->render('physmath');
    }

    public function actionPm1()
    {
        $teachers = Teachers::find()->all();
        $pdfs = Pdfs::find()->all();
        return $this->render('pm1', ['teachers' => $teachers, 'pdfs' => $pdfs]);
    }
    public function actionPm2()
    {
        return $this->render('pm2');
    }
    public function actionPm3()
    {
        return $this->render('pm3');
    }
    public function actionPm4()
    {
        return $this->render('pm4');
    }

    public function actionBc1()
    {
        return $this->render('bc1');
    }
    public function actionBc2()
    {
        return $this->render('bc2');
    }
    public function actionBc3()
    {
        return $this->render('bc3');
    }
    public function actionBc4()
    {
        return $this->render('bc4');
    }

    public function actionH1()
    {
        return $this->render('h1');
    }
    public function actionH2()
    {
        return $this->render('h2');
    }
    public function actionH3()
    {
        return $this->render('h3');
    }
    public function actionH4()
    {
        return $this->render('h4');
    }

    public function actionBiochem()
    {
        return $this->render('biochem');
    }

    public function actionHuman()
    {
        return $this->render('human');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/add.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/** @var yii\web\View $this */

$this->title = 'Добавить';
$this->params['breadcrumbs'][] = ['label' => 'ФизМат', 'url' => ['physmath']];
$this->params['breadcrumbs'][] = ['label' => 'Физика', 'url' => ['pm1']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-index">

  <?php if(yii::$app->session->hasFlash('message')):?>
    <div class="alert alert-dismissible alert-success">
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
      <?php echo yii::$app->session->getFlash('message');?>
    </div>
    
  <?php endif;?>

    <div class="body-content">
        <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']])?>
    	<div class="card bg-light mb-3" style="max-width: 100rem;">
          <div class="card-header">
                <?php $items = ['учитель'=>'учитель', 'практикант'=>'практикант', 'глава'=>'глава'];?>
                <?= $form->field($teacher, 'rank')->dropDownList($items, ['prompt' => 'Выбрать'])->label('Должность');?>
            </div>
          
          <div class="card-body">

            <p>Фото</p>
            <?= $form->field($teacher, 'file')->fileInput()->label('');?>
            <?= $form->field($teacher, 'name')->label('Имя');?>
            <?= $form->field($teacher, 'description')->textarea(['rows' => '6'])->label('Описание');?>
            <p>Научные работы</p>

            
            
            <?= $form->field($pdf, 'file')->fileInput()->label('');?>
            <div class="col-lg-3">
                <?= Html::submitButton('Добавить', ['class'=>'btn btn-primary']);?>
            </div>
            <div class="col-lg-2">
                <a href=<?php echo Url::base(true)."/site/pm1"; ?> class="btn btn-danger" style = "margin-top: 20px;">Назад</a>
            </div>
          </div>
        </div>
        <?php ActiveForm::end()?>
    </div>


    
</div>

views/site/bc1.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Биология';
$this->params['breadcrumbs'][] = ['label' => 'БиоХим', 'url' => ['biochem']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <nav class="navbar navbar-expand-lg bg-light" data-bs-theme="light">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="/baishev/web/site/biochem">БиоХим</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarColor03">
	      <ul class="navbar-nav me-auto">
	        
	        <li class="nav-item dropdown">
	          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Курсы</a>
	          <div class="dropdown-menu">
	            <a class="dropdown-item" href="/baishev/web/site/bc1">Биология</a>
	            <a class="dropdown-item" href="/baishev/web/site/bc2">Химия</a>
	            <a class="dropdown-item" href="/baishev/web/site/bc3">Нейробиология</a>
	            <a class="dropdown-item" href="/baishev/web/site/bc4">Современная Медицина</a>
	          </div>
	        </li>
	      </ul>
	      <form class="d-flex">
	        <input class="form-control me-sm-2" type="search" placeholder="Search">
	        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
	      </form>
	    </div>
	  </div>
	</nav>
    
	<h1>BIOLOGY PAGE</h1>

</div>

views/site/bc2.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Химия';
$this->params['breadcrumbs'][] = ['label' => 'БиоХим', 'url' => ['biochem']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <nav class="navbar navbar-expand-lg bg-light" data-bs-theme="light">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="/baishev/web/site/biochem">БиоХим</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarColor03">
	      <ul class="navbar-nav me-auto">
	        
	        <li class="nav-item dropdown">
	          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Курсы</a>
	          <div class="dropdown-menu">
	            <a class="dropdown-item" href="/baishev/web/site/bc1">Биология</a>
	            <a class="dropdown-item" href="/baishev/web/site/bc2">Химия</a>
	            <a class="dropdown-item" href="/baishev/web/site/bc3">Нейробиология</a>
	            <a class="dropdown-item" href="/baishev/web/site/bc4">Современная Медицина</a>
	          </div>
	        </li>
	      </ul>
	      <form class="d-flex">
	        <input class="form-control me-sm-2" type="search" placeholder="Search">
	        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
	      </form>
	    </div>
	  </div>
	</nav>
    
	<h1>CHEMISTRY PAGE</h1>

</div>

views/site/bc3.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Нейробиология';
$this->params['breadcrumbs'][] = ['label' => 'БиоХим', 'url' => ['biochem']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <nav class="navbar navbar-expand-lg bg-light" data-bs-theme="light">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="/baishev/web/site/biochem">БиоХим</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarColor03">
	      <ul class="navbar-nav me-auto">
	        
	        <li class="nav-item dropdown">
	          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Курсы</a>
	          <div class="dropdown-menu">
	            <a class="dropdown-item" href="/baishev/web/site/bc1">Биология</a>
	            <a class="dropdown-item" href="/baishev/web/site/bc2">Химия</a>
	            <a class="dropdown-item" href="/baishev/web/site/bc3">Нейробиология</a>
	            <a class="dropdown-item" href="/baishev/web/site/bc4">Современная Медицина</a>
	          </div>
	        </li>
	      </ul>
	      <form class="d-flex">
	        <input class="form-control me-sm-2" type="search" placeholder="Search">
	        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
	      </form>
	    </div>
	  </div>
	</nav>
    
	<h1>NEURO-SCIENCE PAGE</h1>

</div>

views/site/bc4.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Современная Медицина';
$this->params['breadcrumbs'][] = ['label' => 'БиоХим', 'url' => ['biochem']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <nav class="navbar navbar-expand-lg bg-light" data-bs-theme="light">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="/baishev/web/site/biochem">БиоХим</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarColor03">
	      <ul class="navbar-nav me-auto">
	        
	        <li class="nav-item dropdown">
	          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Курсы</a>
	          <div class="dropdown-menu">
	            <a class="dropdown-item" href="/baishev/web/site/bc1">Биология</a>
	            <a class="dropdown-item" href="/baishev/web/site/bc2">Химия</a>
	            <a class="dropdown-item" href="/baishev/web/site/bc3">Нейробиология</a>
	            <a class="dropdown-item" href="/baishev/web/site/bc4">Современная Медицина</a>
	          </div>
	        </li>
	      </ul>
	      <form class="d-flex">
	        <input class="form-control me-sm-2" type="search" placeholder="Search">
	        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
	      </form>
	    </div>
	  </div>
	</nav>
    
	<h1>MODERN MEDICINE PAGE</h1>

</div>

views/site/contact.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap5\ActiveForm $form */
/** @var app\models\ContactForm $model */

use yii\bootstrap5\ActiveForm;
use yii\bootstrap5\Html;
use yii\captcha\Captcha;

$this->title = 'Контакты';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::class, [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/h4.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Политика';
$this->params['breadcrumbs'][] = ['label' => 'Гуманитарий', 'url' => ['human']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <nav class="navbar navbar-expand-lg bg-light" data-bs-theme="light">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="/baishev/web/site/human">Гуманитарий</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarColor03">
	      <ul class="navbar-nav me-auto">
	        
	        <li class="nav-item dropdown">
	          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Курсы</a>
	          <div class="dropdown-menu">
	            <a class="dropdown-item" href="/baishev/web/site/h1">История</a>
	            <a class="dropdown-item" href="/baishev/web/site/h2">Психология</a>
	            <a class="dropdown-item" href="/baishev/web/site/h3">Юрисприденция</a>
	            <a class="dropdown-item" href="/baishev/web/site/h4">Политика</a>
	          </div>
	        </li>
	      </ul>
	      <form class="d-flex">
	        <input class="form-control me-sm-2" type="search" placeholder="Search">
	        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
	      </form>
	    </div>
	  </div>
	</nav>
    
	<h1>POLITICS PAGE</h1>

</div>

views/site/login.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap5\ActiveForm $form */

/** @var app\models\LoginForm $model */

use yii\bootstrap5\ActiveForm;
use yii\bootstrap5\Html;

$this->title = 'Логин';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">

            <?php $form = ActiveForm::begin([
                'id' => 'login-form',
                'fieldConfig' => [
                    'template' => "{label}\n{input}\n{error}",
                    'labelOptions' => ['class' => 'col-lg-1 col-form-label mr-lg-3'],
                    'inputOptions' => ['class' => 'col-lg-3 form-control'],
                    'errorOptions' => ['class' => 'col-lg-7 invalid-feedback'],
                ],
            ]); ?>

            <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'password')->passwordInput() ?>

            <?= $form->field($model, 'rememberMe')->checkbox([
                'template' => "<div class=\"custom-control custom-checkbox\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
            ]) ?>

            <div class="form-group">
                <div>
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>
            </div>

            <?php ActiveForm::end(); ?>

            <div style="color:#999;">
                You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
            </div>

        </div>
    </div>
</div>

views/site/update.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/** @var yii\web\View $this */

$this->title = 'Изменить';
$this->params['breadcrumbs'][] = ['label' => 'ФизМат', 'url' => ['physmath']];
$this->params['breadcrumbs'][] = ['label' => 'Физика', 'url' => ['pm1']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-index">

    <?php if(yii::$app->session->hasFlash('message')):?>
        <div class="alert alert-dismissible alert-success">
          <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
          <?php echo yii::$app->session->getFlash('message');?>
        </div>
        
      <?php endif;?>

    <div class="body-content">
        <?php $form = ActiveForm::begin()?>
        <div class="card bg-light mb-3" style="max-width: 100rem;">
          <div class="card-header">
                <?php $items = ['учитель'=>'учитель', 'практикант'=>'практикант', 'глава'=>'глава'];?>
                <?= $form->field($teacher, 'rank')->dropDownList($items, ['prompt' => 'Выбрать'])->label('Должность');?>
            </div>
          
          <div class="card-body">

            <img src="<?= Url::base(true).$teacher->photo; ?>" alt="" width="300px" />

            <br>
            <br>
            <p>Изменить фото</p>
            <?= $form->field($teacher, 'file')->fileInput()->label('');?>

            <?= $form->field($teacher, 'name')->label('Имя');?>

            <?= $form->field($teacher, 'description')->textarea(['rows' => '6'])->label('Описание');?>

            <p>Научные работы</p>

            <?php if(count($pdfs) > 0)?>
            <?php foreach($pdfs as $pdf): ?>
                <?php if($pdf->teachername == $teacher->name):?>
                    <p class="card-text">
                        <?php echo $pdf->pdfname; ?>
                        <span><?= Html:: a('X', ['delete2', 'tid' => $teacher->id, 'pdfid' => $pdf->id], ['class' => 'btn btn-danger', 'style' => 'margin: 10px;']) ?></span>
                    </p>
                <?php endif;?>
            <?php endforeach; ?>
            
            <?= $form->field($pdf, 'file')->fileInput()->label('');?>

            <div class="col-lg-3">
                <?= Html::submitButton('Изменить', ['class'=>'btn btn-warning']);?>
            </div>

            <div class="col-lg-2">
                <a href=<?php echo Url::base(true)."/site/pm1"; ?> class="btn btn-danger" style = "margin-top: 20px;">Назад</a>
            </div>

          </div>

        </div>
        <?php ActiveForm::end()?>
    </div>  
</div>

views/site/view.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/** @var yii\web\View $this */

$this->title = $teacher->name;
$this->params['breadcrumbs'][] = ['label' => 'ФизМат', 'url' => ['physmath']];
$this->params['breadcrumbs'][] = ['label' => 'Физика', 'url' => ['pm1']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-index">

	<div class="card bg-light mb-3" style="max-width: 100rem;">
	  <div class="card-header">Ранк: <?php echo $teacher->rank; ?></div>

	  <div class="card-body">
	  	<img src="<?= Url::base(true).$teacher->photo; ?>" alt="" width="300px" />

	    <h4 class="card-title"><?php echo $teacher->name; ?></h4>
	    <p class="card-text"><?php echo $teacher->description; ?></p>

	    <p class="card-text">Научные работы</p>

	    
		<?php if(count($pdfs) > 0)?>
			<?php foreach($pdfs as $pdf): ?>
				<?php if($pdf->teachername == $teacher->name):?>
					<span><?= Html:: a($pdf->pdfname, ['download', 'filename' => $pdf->pdf], ['class' => 'label label-primary', 'style' => 'margin: 10px;']) ?></span>
					<br>
				<?php endif;?>
			<?php endforeach; ?>
		

		<div class="col-lg-2">
            <a href=<?php echo Url::base(true)."/site/pm1"; ?> class="btn btn-danger" style = "margin-top: 20px;">Назад</a>
        </div>
	  </div>
	</div>
</div>